export const paths = {
    // Auth
    LOGIN: '/login',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    // Dashboard
    DASHBOARD: '/',
    // CAMPAIGNS: '/campaigns',
    PROSPECTS: '/prospects',
    PROSPECTS_NEW: '/prospects/new',
    PROSPECTS_EDIT: '/prospects/edit/:id',
    TEMPLATES: '/templates',
    TEMPLATES_NEW: '/templates/new',
    TEMPLATES_EDIT: '/templates/edit/:id',
    SENDERS: '/senders',
    SENDERS_NEW: '/senders/new',
    SENDERS_EDIT: '/senders/edit/:id',
    // DOCUMENTS: '/documents',
    EMAIL_SENDS: '/email-sends',
    ANALYTICS: '/analytics',
    USERS: '/users',
    USERS_NEW: '/users/new',
    USERS_EDIT: '/users/edit/:id',
    SECTORS: '/sectors',
    SECTORS_NEW: '/sectors/new',
    SECTORS_EDIT: '/sectors/edit/:id',
};
